/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    pricing: Pricing;
    proof: Proof;
    work: Work;
    services: Service;
    story: Story;
    process: Process;
    why: Why;
    faq: Faq;
    cta: Cta;
    footer: Footer;
    brand: Brand;
    theme: Theme;
    layout: Layout;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    proof: ProofSelect<false> | ProofSelect<true>;
    work: WorkSelect<false> | WorkSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    story: StorySelect<false> | StorySelect<true>;
    process: ProcessSelect<false> | ProcessSelect<true>;
    why: WhySelect<false> | WhySelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    cta: CtaSelect<false> | CtaSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    brand: BrandSelect<false> | BrandSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    layout: LayoutSelect<false> | LayoutSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The project grid in the Work section. Drag rows to change the order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  title: string;
  category?: string | null;
  year?: string | null;
  /**
   * Cropped to 4:3.
   */
  image?: {
    /**
     * Alt text is set on the image in the Media library.
     */
    media?: (number | null) | Media;
    /**
     * CSS gradient shown when no image is chosen.
     */
    placeholder?: string | null;
  };
  /**
   * Case study URL, or #work to stay on the page.
   */
  href?: string | null;
  showOnSite?: boolean | null;
  /**
   * Filled from the title if left empty.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every image used on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image as you would to someone who cannot see it. Read aloud by screen readers.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Shown under your name in the sidebar.
   */
  role?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  category?: T;
  year?: T;
  image?:
    | T
    | {
        media?: T;
        placeholder?: T;
      };
  href?: T;
  showOnSite?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The dark full-screen opening: photo, wordmark, intro line, button and rating.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * Full-bleed photo. Also used, blurred, as the page background. Landscape, at least 1600px wide.
   */
  image?: {
    /**
     * Alt text is set on the image in the Media library.
     */
    media?: (number | null) | Media;
    /**
     * CSS gradient shown when no image is chosen.
     */
    placeholder?: string | null;
  };
  wordmarkStyle?: ('logo' | 'text') | null;
  headline1?: string | null;
  /**
   * The mark from Brand (e.g. ®) is added after this line.
   */
  headline2?: string | null;
  descriptor: string;
  cta: {
    label: string;
    href: string;
  };
  rating?: {
    /**
     * Only switch this on with a real rating from your Google Business profile.
     */
    show?: boolean | null;
    score?: number | null;
    /**
     * For your reference, not shown.
     */
    source?: string | null;
    label?: string | null;
  };
  /**
   * Bottom-left of the hero, e.g. ©2026.
   */
  copyright?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * How you charge: a heading, a statement and a supporting note card.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  /**
   * Small uppercase label shown with the ///// motif at the top of the section.
   */
  label: string;
  /**
   * Large heading under the label. Leave empty to hide it.
   */
  heading?: string | null;
  statement: string;
  /**
   * Shown in grey straight after the statement.
   */
  statementMuted?: string | null;
  note?: {
    title?: string | null;
    body?: string | null;
  };
  button: {
    label: string;
    href: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The row of three cards: a stat, a testimonial and client logos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof".
 */
export interface Proof {
  id: number;
  /**
   * Small uppercase label shown with the ///// motif at the top of the section.
   */
  label: string;
  stat: {
    label: string;
    /**
     * e.g. $
     */
    prefix?: string | null;
    /**
     * Counts up from 0 on scroll.
     */
    value: number;
    /**
     * e.g. % or M+ (accent).
     */
    suffix?: string | null;
    caption?: string | null;
    /**
     * Smaller figures listed under the big number.
     */
    more?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  testimonial: {
    /**
     * Without quote marks.
     */
    quote: string;
    name: string;
    company?: string | null;
  };
  logosLabel?: string | null;
  /**
   * Designed for 6. Without an image, the name shows as a text wordmark.
   */
  logos?:
    | {
        name: string;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading for the project grid. The projects themselves are under Projects.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work".
 */
export interface Work {
  id: number;
  /**
   * Small uppercase label shown with the ///// motif at the top of the section.
   */
  label: string;
  /**
   * Large heading under the label. Leave empty to hide it.
   */
  heading?: string | null;
  /**
   * Optional short paragraph under the heading.
   */
  intro?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Small uppercase label shown with the ///// motif at the top of the section.
   */
  label: string;
  /**
   * Large heading under the label. Leave empty to hide it.
   */
  heading?: string | null;
  /**
   * Numbered automatically in this order. Drag to reorder.
   */
  items?:
    | {
        title: string;
        description: string;
        /**
         * Optional small line under the description, e.g. Meta · TikTok · Google.
         */
        tags?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story".
 */
export interface Story {
  id: number;
  /**
   * Small uppercase label shown with the ///// motif at the top of the section.
   */
  label: string;
  /**
   * The small person chip. Leave the name empty to hide it.
   */
  founder?: {
    name?: string | null;
    title?: string | null;
    /**
     * Square, at least 96×96. Shown as a small circle.
     */
    avatar?: {
      /**
       * Alt text is set on the image in the Media library.
       */
      media?: (number | null) | Media;
      /**
       * CSS gradient shown when no image is chosen.
       */
      placeholder?: string | null;
    };
  };
  statement: string;
  /**
   * Shown in grey straight after the statement.
   */
  statementMuted?: string | null;
  button: {
    label: string;
    href: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process".
 */
export interface Process {
  id: number;
  /**
   * Small uppercase label shown with the ///// motif at the top of the section.
   */
  label: string;
  /**
   * Large heading under the label. Leave empty to hide it.
   */
  heading?: string | null;
  /**
   * Designed for 4 steps (4 → 2 → 1 columns).
   */
  steps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A grid of reasons to choose you. Designed for 4.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why".
 */
export interface Why {
  id: number;
  /**
   * Small uppercase label shown with the ///// motif at the top of the section.
   */
  label: string;
  /**
   * Large heading under the label. Leave empty to hide it.
   */
  heading?: string | null;
  items?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  /**
   * Small uppercase label shown with the ///// motif at the top of the section.
   */
  label: string;
  /**
   * Large heading under the label. Leave empty to hide it.
   */
  heading?: string | null;
  /**
   * The first question starts open.
   */
  items?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The dark band before the footer. Your email from Brand is shown next to the button.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta".
 */
export interface Cta {
  id: number;
  /**
   * Small uppercase label shown with the ///// motif at the top of the section.
   */
  label: string;
  /**
   * Around 45 characters reads best.
   */
  headline: string;
  /**
   * Optional line under the headline.
   */
  body?: string | null;
  button: {
    label: string;
    href: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Also listed in the menu.
   */
  socials?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  legal?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand".
 */
export interface Brand {
  id: number;
  brand: {
    name: string;
    /**
     * e.g. Studio
     */
    suffix?: string | null;
    /**
     * Accent mark
     */
    mark?: string | null;
    /**
     * Top bar, hero and footer. SVG or transparent PNG; it is recoloured to fit each section.
     */
    logo?: (number | null) | Media;
    /**
     * Compact mark, used in the admin and anywhere space is tight.
     */
    logoMark?: (number | null) | Media;
    /**
     * Shown in the footer.
     */
    tagline?: string | null;
    email: string;
    /**
     * Leave empty to hide.
     */
    location?: string | null;
    /**
     * For the live clock in the top bar. Leave empty to hide the clock.
     */
    timezone?:
      | (
          | 'Africa/Abidjan'
          | 'Africa/Accra'
          | 'Africa/Addis_Ababa'
          | 'Africa/Algiers'
          | 'Africa/Asmera'
          | 'Africa/Bamako'
          | 'Africa/Bangui'
          | 'Africa/Banjul'
          | 'Africa/Bissau'
          | 'Africa/Blantyre'
          | 'Africa/Brazzaville'
          | 'Africa/Bujumbura'
          | 'Africa/Cairo'
          | 'Africa/Casablanca'
          | 'Africa/Ceuta'
          | 'Africa/Conakry'
          | 'Africa/Dakar'
          | 'Africa/Dar_es_Salaam'
          | 'Africa/Djibouti'
          | 'Africa/Douala'
          | 'Africa/El_Aaiun'
          | 'Africa/Freetown'
          | 'Africa/Gaborone'
          | 'Africa/Harare'
          | 'Africa/Johannesburg'
          | 'Africa/Juba'
          | 'Africa/Kampala'
          | 'Africa/Khartoum'
          | 'Africa/Kigali'
          | 'Africa/Kinshasa'
          | 'Africa/Lagos'
          | 'Africa/Libreville'
          | 'Africa/Lome'
          | 'Africa/Luanda'
          | 'Africa/Lubumbashi'
          | 'Africa/Lusaka'
          | 'Africa/Malabo'
          | 'Africa/Maputo'
          | 'Africa/Maseru'
          | 'Africa/Mbabane'
          | 'Africa/Mogadishu'
          | 'Africa/Monrovia'
          | 'Africa/Nairobi'
          | 'Africa/Ndjamena'
          | 'Africa/Niamey'
          | 'Africa/Nouakchott'
          | 'Africa/Ouagadougou'
          | 'Africa/Porto-Novo'
          | 'Africa/Sao_Tome'
          | 'Africa/Tripoli'
          | 'Africa/Tunis'
          | 'Africa/Windhoek'
          | 'America/Adak'
          | 'America/Anchorage'
          | 'America/Anguilla'
          | 'America/Antigua'
          | 'America/Araguaina'
          | 'America/Argentina/La_Rioja'
          | 'America/Argentina/Rio_Gallegos'
          | 'America/Argentina/Salta'
          | 'America/Argentina/San_Juan'
          | 'America/Argentina/San_Luis'
          | 'America/Argentina/Tucuman'
          | 'America/Argentina/Ushuaia'
          | 'America/Aruba'
          | 'America/Asuncion'
          | 'America/Bahia'
          | 'America/Bahia_Banderas'
          | 'America/Barbados'
          | 'America/Belem'
          | 'America/Belize'
          | 'America/Blanc-Sablon'
          | 'America/Boa_Vista'
          | 'America/Bogota'
          | 'America/Boise'
          | 'America/Buenos_Aires'
          | 'America/Cambridge_Bay'
          | 'America/Campo_Grande'
          | 'America/Cancun'
          | 'America/Caracas'
          | 'America/Catamarca'
          | 'America/Cayenne'
          | 'America/Cayman'
          | 'America/Chicago'
          | 'America/Chihuahua'
          | 'America/Ciudad_Juarez'
          | 'America/Coral_Harbour'
          | 'America/Cordoba'
          | 'America/Costa_Rica'
          | 'America/Coyhaique'
          | 'America/Creston'
          | 'America/Cuiaba'
          | 'America/Curacao'
          | 'America/Danmarkshavn'
          | 'America/Dawson'
          | 'America/Dawson_Creek'
          | 'America/Denver'
          | 'America/Detroit'
          | 'America/Dominica'
          | 'America/Edmonton'
          | 'America/Eirunepe'
          | 'America/El_Salvador'
          | 'America/Fort_Nelson'
          | 'America/Fortaleza'
          | 'America/Glace_Bay'
          | 'America/Godthab'
          | 'America/Goose_Bay'
          | 'America/Grand_Turk'
          | 'America/Grenada'
          | 'America/Guadeloupe'
          | 'America/Guatemala'
          | 'America/Guayaquil'
          | 'America/Guyana'
          | 'America/Halifax'
          | 'America/Havana'
          | 'America/Hermosillo'
          | 'America/Indiana/Knox'
          | 'America/Indiana/Marengo'
          | 'America/Indiana/Petersburg'
          | 'America/Indiana/Tell_City'
          | 'America/Indiana/Vevay'
          | 'America/Indiana/Vincennes'
          | 'America/Indiana/Winamac'
          | 'America/Indianapolis'
          | 'America/Inuvik'
          | 'America/Iqaluit'
          | 'America/Jamaica'
          | 'America/Jujuy'
          | 'America/Juneau'
          | 'America/Kentucky/Monticello'
          | 'America/Kralendijk'
          | 'America/La_Paz'
          | 'America/Lima'
          | 'America/Los_Angeles'
          | 'America/Louisville'
          | 'America/Lower_Princes'
          | 'America/Maceio'
          | 'America/Managua'
          | 'America/Manaus'
          | 'America/Marigot'
          | 'America/Martinique'
          | 'America/Matamoros'
          | 'America/Mazatlan'
          | 'America/Mendoza'
          | 'America/Menominee'
          | 'America/Merida'
          | 'America/Metlakatla'
          | 'America/Mexico_City'
          | 'America/Miquelon'
          | 'America/Moncton'
          | 'America/Monterrey'
          | 'America/Montevideo'
          | 'America/Montserrat'
          | 'America/Nassau'
          | 'America/New_York'
          | 'America/Nome'
          | 'America/Noronha'
          | 'America/North_Dakota/Beulah'
          | 'America/North_Dakota/Center'
          | 'America/North_Dakota/New_Salem'
          | 'America/Ojinaga'
          | 'America/Panama'
          | 'America/Paramaribo'
          | 'America/Phoenix'
          | 'America/Port-au-Prince'
          | 'America/Port_of_Spain'
          | 'America/Porto_Velho'
          | 'America/Puerto_Rico'
          | 'America/Punta_Arenas'
          | 'America/Rankin_Inlet'
          | 'America/Recife'
          | 'America/Regina'
          | 'America/Resolute'
          | 'America/Rio_Branco'
          | 'America/Santarem'
          | 'America/Santiago'
          | 'America/Santo_Domingo'
          | 'America/Sao_Paulo'
          | 'America/Scoresbysund'
          | 'America/Sitka'
          | 'America/St_Barthelemy'
          | 'America/St_Johns'
          | 'America/St_Kitts'
          | 'America/St_Lucia'
          | 'America/St_Thomas'
          | 'America/St_Vincent'
          | 'America/Swift_Current'
          | 'America/Tegucigalpa'
          | 'America/Thule'
          | 'America/Tijuana'
          | 'America/Toronto'
          | 'America/Tortola'
          | 'America/Vancouver'
          | 'America/Whitehorse'
          | 'America/Winnipeg'
          | 'America/Yakutat'
          | 'Antarctica/Casey'
          | 'Antarctica/Davis'
          | 'Antarctica/DumontDUrville'
          | 'Antarctica/Macquarie'
          | 'Antarctica/Mawson'
          | 'Antarctica/McMurdo'
          | 'Antarctica/Palmer'
          | 'Antarctica/Rothera'
          | 'Antarctica/Syowa'
          | 'Antarctica/Troll'
          | 'Antarctica/Vostok'
          | 'Arctic/Longyearbyen'
          | 'Asia/Aden'
          | 'Asia/Almaty'
          | 'Asia/Amman'
          | 'Asia/Anadyr'
          | 'Asia/Aqtau'
          | 'Asia/Aqtobe'
          | 'Asia/Ashgabat'
          | 'Asia/Atyrau'
          | 'Asia/Baghdad'
          | 'Asia/Bahrain'
          | 'Asia/Baku'
          | 'Asia/Bangkok'
          | 'Asia/Barnaul'
          | 'Asia/Beirut'
          | 'Asia/Bishkek'
          | 'Asia/Brunei'
          | 'Asia/Calcutta'
          | 'Asia/Chita'
          | 'Asia/Colombo'
          | 'Asia/Damascus'
          | 'Asia/Dhaka'
          | 'Asia/Dili'
          | 'Asia/Dubai'
          | 'Asia/Dushanbe'
          | 'Asia/Famagusta'
          | 'Asia/Gaza'
          | 'Asia/Hebron'
          | 'Asia/Hong_Kong'
          | 'Asia/Hovd'
          | 'Asia/Irkutsk'
          | 'Asia/Jakarta'
          | 'Asia/Jayapura'
          | 'Asia/Jerusalem'
          | 'Asia/Kabul'
          | 'Asia/Kamchatka'
          | 'Asia/Karachi'
          | 'Asia/Katmandu'
          | 'Asia/Khandyga'
          | 'Asia/Krasnoyarsk'
          | 'Asia/Kuala_Lumpur'
          | 'Asia/Kuching'
          | 'Asia/Kuwait'
          | 'Asia/Macau'
          | 'Asia/Magadan'
          | 'Asia/Makassar'
          | 'Asia/Manila'
          | 'Asia/Muscat'
          | 'Asia/Nicosia'
          | 'Asia/Novokuznetsk'
          | 'Asia/Novosibirsk'
          | 'Asia/Omsk'
          | 'Asia/Oral'
          | 'Asia/Phnom_Penh'
          | 'Asia/Pontianak'
          | 'Asia/Pyongyang'
          | 'Asia/Qatar'
          | 'Asia/Qostanay'
          | 'Asia/Qyzylorda'
          | 'Asia/Rangoon'
          | 'Asia/Riyadh'
          | 'Asia/Saigon'
          | 'Asia/Sakhalin'
          | 'Asia/Samarkand'
          | 'Asia/Seoul'
          | 'Asia/Shanghai'
          | 'Asia/Singapore'
          | 'Asia/Srednekolymsk'
          | 'Asia/Taipei'
          | 'Asia/Tashkent'
          | 'Asia/Tbilisi'
          | 'Asia/Tehran'
          | 'Asia/Thimphu'
          | 'Asia/Tokyo'
          | 'Asia/Tomsk'
          | 'Asia/Ulaanbaatar'
          | 'Asia/Urumqi'
          | 'Asia/Ust-Nera'
          | 'Asia/Vientiane'
          | 'Asia/Vladivostok'
          | 'Asia/Yakutsk'
          | 'Asia/Yekaterinburg'
          | 'Asia/Yerevan'
          | 'Atlantic/Azores'
          | 'Atlantic/Bermuda'
          | 'Atlantic/Canary'
          | 'Atlantic/Cape_Verde'
          | 'Atlantic/Faeroe'
          | 'Atlantic/Madeira'
          | 'Atlantic/Reykjavik'
          | 'Atlantic/South_Georgia'
          | 'Atlantic/St_Helena'
          | 'Atlantic/Stanley'
          | 'Australia/Adelaide'
          | 'Australia/Brisbane'
          | 'Australia/Broken_Hill'
          | 'Australia/Darwin'
          | 'Australia/Eucla'
          | 'Australia/Hobart'
          | 'Australia/Lindeman'
          | 'Australia/Lord_Howe'
          | 'Australia/Melbourne'
          | 'Australia/Perth'
          | 'Australia/Sydney'
          | 'Europe/Amsterdam'
          | 'Europe/Andorra'
          | 'Europe/Astrakhan'
          | 'Europe/Athens'
          | 'Europe/Belgrade'
          | 'Europe/Berlin'
          | 'Europe/Bratislava'
          | 'Europe/Brussels'
          | 'Europe/Bucharest'
          | 'Europe/Budapest'
          | 'Europe/Busingen'
          | 'Europe/Chisinau'
          | 'Europe/Copenhagen'
          | 'Europe/Dublin'
          | 'Europe/Gibraltar'
          | 'Europe/Guernsey'
          | 'Europe/Helsinki'
          | 'Europe/Isle_of_Man'
          | 'Europe/Istanbul'
          | 'Europe/Jersey'
          | 'Europe/Kaliningrad'
          | 'Europe/Kiev'
          | 'Europe/Kirov'
          | 'Europe/Lisbon'
          | 'Europe/Ljubljana'
          | 'Europe/London'
          | 'Europe/Luxembourg'
          | 'Europe/Madrid'
          | 'Europe/Malta'
          | 'Europe/Mariehamn'
          | 'Europe/Minsk'
          | 'Europe/Monaco'
          | 'Europe/Moscow'
          | 'Europe/Oslo'
          | 'Europe/Paris'
          | 'Europe/Podgorica'
          | 'Europe/Prague'
          | 'Europe/Riga'
          | 'Europe/Rome'
          | 'Europe/Samara'
          | 'Europe/San_Marino'
          | 'Europe/Sarajevo'
          | 'Europe/Saratov'
          | 'Europe/Simferopol'
          | 'Europe/Skopje'
          | 'Europe/Sofia'
          | 'Europe/Stockholm'
          | 'Europe/Tallinn'
          | 'Europe/Tirane'
          | 'Europe/Ulyanovsk'
          | 'Europe/Vaduz'
          | 'Europe/Vatican'
          | 'Europe/Vienna'
          | 'Europe/Vilnius'
          | 'Europe/Volgograd'
          | 'Europe/Warsaw'
          | 'Europe/Zagreb'
          | 'Europe/Zurich'
          | 'Indian/Antananarivo'
          | 'Indian/Chagos'
          | 'Indian/Christmas'
          | 'Indian/Cocos'
          | 'Indian/Comoro'
          | 'Indian/Kerguelen'
          | 'Indian/Mahe'
          | 'Indian/Maldives'
          | 'Indian/Mauritius'
          | 'Indian/Mayotte'
          | 'Indian/Reunion'
          | 'Pacific/Apia'
          | 'Pacific/Auckland'
          | 'Pacific/Bougainville'
          | 'Pacific/Chatham'
          | 'Pacific/Easter'
          | 'Pacific/Efate'
          | 'Pacific/Enderbury'
          | 'Pacific/Fakaofo'
          | 'Pacific/Fiji'
          | 'Pacific/Funafuti'
          | 'Pacific/Galapagos'
          | 'Pacific/Gambier'
          | 'Pacific/Guadalcanal'
          | 'Pacific/Guam'
          | 'Pacific/Honolulu'
          | 'Pacific/Kiritimati'
          | 'Pacific/Kosrae'
          | 'Pacific/Kwajalein'
          | 'Pacific/Majuro'
          | 'Pacific/Marquesas'
          | 'Pacific/Midway'
          | 'Pacific/Nauru'
          | 'Pacific/Niue'
          | 'Pacific/Norfolk'
          | 'Pacific/Noumea'
          | 'Pacific/Pago_Pago'
          | 'Pacific/Palau'
          | 'Pacific/Pitcairn'
          | 'Pacific/Ponape'
          | 'Pacific/Port_Moresby'
          | 'Pacific/Rarotonga'
          | 'Pacific/Saipan'
          | 'Pacific/Tahiti'
          | 'Pacific/Tarawa'
          | 'Pacific/Tongatapu'
          | 'Pacific/Truk'
          | 'Pacific/Wake'
          | 'Pacific/Wallis'
        )
      | null;
    availability?: {
      active?: boolean | null;
      label?: string | null;
    };
  };
  seo: {
    title: string;
    /**
     * Shown under the title in search results. Aim for 120–160 characters.
     */
    description?: string | null;
    /**
     * 1200×630 JPG or PNG. Shown when the link is shared.
     */
    ogImage?: (number | null) | Media;
    /**
     * e.g. en, en-GB, fr.
     */
    lang?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Colours, fonts and corner radius for the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * Buttons, ® mark, highlights.
   */
  accent: string;
  /**
   * Hero, CTA band, text.
   */
  dark: string;
  /**
   * Page background.
   */
  light: string;
  /**
   * Card backgrounds.
   */
  card: string;
  /**
   * Lines and secondary text (darkened automatically for contrast).
   */
  grey: string;
  fontDisplay: string;
  fontBody: string;
  /**
   * The device frame. Cards use 60% of this.
   */
  radius: number;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout".
 */
export interface Layout {
  id: number;
  /**
   * Drag to change the order of sections on the page. Open a row and untick to hide it. The footer always stays last.
   */
  sections?:
    | {
        section:
          'hero' | 'pricing' | 'proof' | 'work' | 'services' | 'story' | 'process' | 'why' | 'faq' | 'cta' | 'footer';
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Links to hidden sections are removed from the menu automatically.
   */
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  ui: {
    menuTitle: string;
    menuOpen: string;
    menuClose: string;
    footerLinksTitle: string;
    footerSocialsTitle: string;
    footerContactTitle: string;
    /**
     * {n} becomes 01, 02…
     */
    counter: string;
    motif: string;
    backToTop: string;
    skipToContent: string;
    localTime: string;
    viewProject: string;
    /**
     * {score} becomes the rating.
     */
    ratingOutOf: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  image?:
    | T
    | {
        media?: T;
        placeholder?: T;
      };
  wordmarkStyle?: T;
  headline1?: T;
  headline2?: T;
  descriptor?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  rating?:
    | T
    | {
        show?: T;
        score?: T;
        source?: T;
        label?: T;
      };
  copyright?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  statement?: T;
  statementMuted?: T;
  note?:
    | T
    | {
        title?: T;
        body?: T;
      };
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof_select".
 */
export interface ProofSelect<T extends boolean = true> {
  label?: T;
  stat?:
    | T
    | {
        label?: T;
        prefix?: T;
        value?: T;
        suffix?: T;
        caption?: T;
        more?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  testimonial?:
    | T
    | {
        quote?: T;
        name?: T;
        company?: T;
      };
  logosLabel?: T;
  logos?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work_select".
 */
export interface WorkSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  intro?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        tags?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story_select".
 */
export interface StorySelect<T extends boolean = true> {
  label?: T;
  founder?:
    | T
    | {
        name?: T;
        title?: T;
        avatar?:
          | T
          | {
              media?: T;
              placeholder?: T;
            };
      };
  statement?: T;
  statementMuted?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process_select".
 */
export interface ProcessSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why_select".
 */
export interface WhySelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  items?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta_select".
 */
export interface CtaSelect<T extends boolean = true> {
  label?: T;
  headline?: T;
  body?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  legal?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand_select".
 */
export interface BrandSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        suffix?: T;
        mark?: T;
        logo?: T;
        logoMark?: T;
        tagline?: T;
        email?: T;
        location?: T;
        timezone?: T;
        availability?:
          | T
          | {
              active?: T;
              label?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        lang?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  accent?: T;
  dark?: T;
  light?: T;
  card?: T;
  grey?: T;
  fontDisplay?: T;
  fontBody?: T;
  radius?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout_select".
 */
export interface LayoutSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        section?: T;
        visible?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ui?:
    | T
    | {
        menuTitle?: T;
        menuOpen?: T;
        menuClose?: T;
        footerLinksTitle?: T;
        footerSocialsTitle?: T;
        footerContactTitle?: T;
        counter?: T;
        motif?: T;
        backToTop?: T;
        skipToContent?: T;
        localTime?: T;
        viewProject?: T;
        ratingOutOf?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}